name: Code Testing

# TODO: code coverage rebuild

on:
  workflow_call:
    inputs:
      cache_key:
        description: "PHP extensions cache key"
        required: true
        type: string
      php:
        description: "PHP version to run on"
        required: false
        default: "8.1"
        type: string
      extensions:
        description: "PHP extensions"
        default: opcache, simplexml, mbstring
        required: false
        type: string
      tools:
        description: "PHP tools"
        required: false
        default: composer, cs2pr, phpunit/phpunit
        type: string
      ini_values:
        description: "PHP ini values"
        default: max_execution_time=180, date.timezone=Asia/Tbilisi
        required: false
        type: string

jobs:
  tests:
    timeout-minutes: 15
    if: github.event.pull_request.draft == false
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ ${{ inputs.php }} ]
    outputs:
      min_coverage: ${{ steps.coverage_data.outputs.min_coverage }}
      actual_coverage: ${{ steps.coverage_data.outputs.actual_coverage }}
      result_coverage: ${{ steps.coverage_data.outputs.result_coverage }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cache environment
        id: ext-cache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ inputs.extensions }}
          key: ${{ inputs.cache_key }}

      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.ext-cache.outputs.dir }}
          key: ${{ steps.ext-cache.outputs.key }}
          restore-keys: ${{ steps.ext-cache.outputs.key }}

      - name: Setup PHP version ${{ matrix.php-version }} on ${{ matrix.os }}
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ inputs.extensions }}
          tools: ${{ inputs.tools }}
          coverage: xdebug
          ini-values: ${{ inputs.ini_values }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          update: true

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Composer Install
        id: composer-install
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "locked"
          composer-options: "--prefer-dist"

      - name: Run test suite
        run: phpunit

      - name: Get coverage data
        id: coverage-data
        if: always()
        run: |
          highLowerBound=`php ./.github/scripts/code_coverage.php highLowerBound`
          actualCoverage=`php ./.github/scripts/code_coverage.php actualCoverage`
          echo "::set-output name=min_coverage::$highLowerBound"
          echo "::set-output name=actual_coverage::$actualCoverage"
          echo "::set-output name=result_coverage::$(($actualCoverage < $highLowerBound))"

      - name: Code Coverage Check
        if: ${{ always() && steps.coverage-data.outputs.result_coverage != 0 }}
        run: |
          echo Your code coverage \
          ${{ steps.coverage-data.outputs.actual_coverage }} % less than \
          ${{ steps.coverage-data.outputs.min_coverage }} % \
          of minimum required bound. See build/coverage/html/index.html
          exit 1
